#%RAML 1.0 NamedExample
values:
-
  
    CUST_ID : 123,
    CUST_FIRST_NAME?: Yusuf,
    CUST_LAST_NAME: Khan,
    CUST_GENDER: M,
    CUST_YEAR_OF_DATE: 1994-02-28,
    CUST_MARITAL_STATUS: Single,
    CUST_STREET_ADDRESS: Aurngabaad,
    CUST_POSTAL_CODE: BH123,
    CUST_CITY: Bihar,
    CUST_COMMENT: XYZ
  
-
  
    CUST_ID : 1234,
    CUST_FIRST_NAME?: Wasim,
    CUST_LAST_NAME: Ansari,
    CUST_GENDER: M,
    CUST_YEAR_OF_DATE: 1993-04-18,
    CUST_MARITAL_STATUS: Single,
    CUST_STREET_ADDRESS: Jsr,
    CUST_POSTAL_CODE: JS223,
    CUST_CITY: Jmshedpur,
    CUST_COMMENT: XYZ
  