#%RAML 1.0 Trait
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
          401:
            description: Unauthorized or Invalid Client application credentials!
          500:
              description: Bad response from authrization sever or WSDL soap flult error!